User managment
xronos-ch/xronos.rails pull request #275
Opened 2023-03-24 15:49 UTC by MartinHinz

2023-03-24 15:50 UTC, MartinHinz commented
Added basic user managment and tests. Some integration tests using javascript had not worked due to problems with selenium, so I removed them again.

2023-03-30 09:23 UTC, joeroe requested changes
For me there were several errors preventing me from submitting the 'new user profile' form:

* user_profile_params is missing `admin`
* "User passphrase is wrong"
* "User can't be blank"

I don't know if you also want to address #266, #267 and (new) #281 before merging?

2023-03-30 09:23 UTC, joeroe commented on app/controllers/user_profiles_controller.rb
> +      {user_attributes: [
Need to add `admin` here.

2023-04-03 12:52 UTC, MartinHinz commented on app/controllers/user_profiles_controller.rb
> +      {user_attributes: [
Thanks, added.

2023-04-03 13:30 UTC, joeroe commented
@MartinHinz Sorry, I meant #277 and #276.

2023-04-04 12:13 UTC, MartinHinz commented
Thanks, now it makes much more sense. Please put this PR aside (I will not like to close it, since the discussion here is very helpful). I will implement your suggestions and come back when finished.

2023-12-18 13:15 UTC, joeroe commented
The above addresses the errors when submitting user profile forms, as well as #277 and #281.

Remaining/new issues relating to user management: #276, #315, #316

2023-12-18 13:17 UTC, merged